version: '3'

services:
  database-service:
    image: ultimate-food-manager/database-service
    restart:
      always
    environment:
      ARANGO_ROOT_PASSWORD: "root"
    ports:
      - "8529:8529"
