export const IDENTIFIER = {
	USER_SERVICE: Symbol.for('USER_SERVICE'),
	USER_QUERIES: Symbol.for('USER_QUERIES'),
	USER_MAPPER: Symbol.for('USER_MAPPER'),
	PRODUCT_SERVICE: Symbol.for('PRODUCT_SERVICE'),
	PRODUCT_QUERIES: Symbol.for('PRODUCT_QUERIES'),
	PRODUCT_MAPPER: Symbol.for('PRODUCT_MAPPER'),
	MEDIA_SERVICE: Symbol.for('MEDIA_SERVICE'),
	MEDIA_QUERIES: Symbol.for('MEDIA_QUERIES'),
	MEDIA_MAPPER: Symbol.for('MEDIA_MAPPER')
};

export default IDENTIFIER;
